apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: k8sops-pod-example
    ports:
    - containerPort: 80
    # Following lines were added
    livenessProbe:
      httpGet:
        path: /
        port: 80
    initialDelaySeconds: 15